"""add_filaments

Revision ID: 7a7b8d5cdce8
Revises: c5bc924e94ed
Create Date: 2026-08-18 12:16:43.018498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a7b8d5cdce8'
down_revision = 'c5bc924e94ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('material', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('total_weight_g', sa.Float(), nullable=False),
    sa.Column('remaining_weight_g', sa.Float(), nullable=False),
    sa.Column('assigned_printer_ip', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filaments')
    # ### end Alembic commands ###
