"""add print history

Revision ID: c5bc924e94ed
Revises: 56f0613031a9
Create Date: 2026-08-18 11:09:35.444286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5bc924e94ed'
down_revision = '56f0613031a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('print_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('printer_ip', sa.Text(), nullable=True),
    sa.Column('printer_name', sa.Text(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('print_history')
    # ### end Alembic commands ###
