"""add_filaments_printername

Revision ID: d543239eaae5
Revises: 7a7b8d5cdce8
Create Date: 2026-08-18 14:43:36.059011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd543239eaae5'
down_revision = '7a7b8d5cdce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_printer_name', sa.Text(), nullable=True))
        batch_op.drop_column('assigned_printer_ip')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_printer_ip', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('assigned_printer_name')

    # ### end Alembic commands ###
